version: "3.2"

services:
  dev:
    container_name: test-node
    image: paritytech/ci-linux:eb1f6a26-20220517
    working_dir: /var/www/test-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/test-node/.cargo
    volumes:
      - .:/var/www/test-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/test-node --dev --ws-external"
